"""
Outlander Gear catalog expansion generator
==========================================
Produces product_info_21.md through product_info_100.md (80 new products)
in the same markdown format as the existing 20 products. Outputs to
./product-info/ alongside the original files.

Run:
    python generate_products.py
"""

from pathlib import Path
from textwrap import dedent

OUT_DIR = Path(__file__).parent / "product-info"
OUT_DIR.mkdir(exist_ok=True)


# =========================================================================
# Product catalog — 80 products across 10 categories
# =========================================================================
# Format: (id, name, price, brand, category, features, specs, faq, warranty)

PRODUCTS = [
    # ---------- CLIMBING (21-30) ----------
    (21, "AlpineEdge Climbing Rope", 180, "AlpineEdge", "Climbing Rope",
     ["Dynamic kernmantle construction for shock absorption",
      "60-meter length suitable for single-pitch and multi-pitch routes",
      "9.8mm diameter — balance of weight and durability",
      "Dry treatment for water and abrasion resistance",
      "Middle marker for quick identification during rappels",
      "UIAA and CE certified for climbing safety",
      "Bicolor pattern doubles as middle marker fallback",
      "Smooth handling that resists kinking",
      "Bag included for transport and storage"],
     {"Type": "Single rope (dynamic)", "Length": "60 m", "Diameter": "9.8 mm",
      "Weight per Meter": "62 g/m", "Number of Falls": "8 (UIAA)",
      "Impact Force": "8.5 kN", "Sheath Slippage": "0 mm",
      "Dynamic Elongation": "32%", "Static Elongation": "8%",
      "Dry Treatment": "Yes (sheath and core)", "Color": "Blue/Orange bicolor",
      "Certifications": "UIAA, CE EN 892"},
     [("Is this rope suitable for top-roping at a gym?", "Yes — at 60 m it provides ample length for most gym routes and outdoor single-pitch climbs."),
      ("How often should I retire the rope?", "Inspect after every climb; retire after 5 years of regular use, after a major fall, or any visible damage to the sheath or core.")],
     "1-year limited warranty against manufacturing defects. Covers sheath separation and core defects. Does not cover damage from improper use, falls, or normal wear. Non-transferable."),

    (22, "SummitGrip Climbing Harness", 85, "AlpineEdge", "Climbing Harness",
     ["Adjustable waistbelt and leg loops for custom fit",
      "Four reinforced gear loops for racking equipment",
      "Haul loop on rear for trailing rope",
      "Auto-locking buckle on waistbelt",
      "Breathable mesh padding for all-day comfort",
      "Rated for sport, trad, and alpine climbing",
      "Available in three sizes (S/M/L)",
      "Reflective trim for low-light visibility"],
     {"Best Use": "Sport, Trad, Alpine", "Waist Size": "28-42 in (adjustable)",
      "Leg Loop Size": "20-30 in (adjustable)", "Weight": "395 g",
      "Gear Loops": "4 reinforced", "Haul Loop": "Yes",
      "Buckle Type": "Auto-locking aluminum", "Padding": "EVA foam with mesh cover",
      "Color": "Charcoal/Lime", "Certifications": "UIAA, CE EN 12277"},
     [("Can I use this harness for ice climbing?", "Yes — the leg loops are sized to accommodate winter layering, though dedicated ice harnesses may offer thicker padding."),
      ("How do I size the harness?", "Measure your waist at the hipbone level and consult the size chart. The harness should sit snug at the hips without restricting breathing.")],
     "2-year limited warranty against manufacturing defects in stitching and buckle hardware. Non-transferable."),

    (23, "RockShield Climbing Helmet", 70, "AlpineEdge", "Climbing Helmet",
     ["Lightweight foam-and-shell hybrid construction",
      "Adjustable headband fits a wide range of head sizes",
      "Ventilation channels reduce overheating",
      "Headlamp clips on front and rear",
      "Magnetic chinstrap buckle for one-handed operation",
      "Y-strap webbing for secure fit",
      "Replaceable internal padding",
      "Tested against impacts from above, side, front, and rear"],
     {"Type": "Hybrid (in-mold + ABS shell)", "Head Circumference": "52-62 cm",
      "Weight": "240 g", "Vents": "10", "Headlamp Clips": "4",
      "Padding": "Removable, washable", "Color": "Matte Black",
      "Certifications": "UIAA, CE EN 12492"},
     [("Will this fit over a beanie for ice climbing?", "Yes — the adjustable headband expands to accommodate a thin to mid-weight beanie."),
      ("How long does the helmet last?", "Replace after any significant impact, after 5 years of regular use, or sooner if visible cracks or compression appear in the foam.")],
     "3-year limited warranty against manufacturing defects. Replace after any major impact regardless of visible damage. Non-transferable."),

    (24, "CragMaster Climbing Shoes", 145, "GripWorks", "Climbing Shoes",
     ["Aggressive downturned profile for steep terrain",
      "Sticky rubber compound for maximum friction",
      "Velcro straps for quick on/off",
      "Synthetic upper resists stretching",
      "Reinforced toe box for edging precision",
      "Available in unisex sizes 4-13"],
     {"Closure": "Dual Velcro straps", "Profile": "Aggressive downturn",
      "Rubber": "GripMax 4mm sticky compound", "Upper": "Synthetic microfiber",
      "Last": "Asymmetric", "Best Use": "Sport, bouldering, overhanging routes",
      "Sizes Available": "US 4-13", "Color": "Red/Black"},
     [("Should I size down for performance?", "Many climbers size down 0.5-1 full size from street shoe size for performance fit; cragsters tend to size to street size."),
      ("Can these be resoled?", "Yes — the rubber sole can be replaced by most cobblers specializing in climbing shoes, typically 1-2 times before the shoe loses its shape.")],
     "Limited 6-month warranty against manufacturing defects. Does not cover normal sole wear. Non-transferable."),

    (25, "ChalkPro Bag", 25, "GripWorks", "Climbing Accessories",
     ["Fleece-lined interior holds chalk longer",
      "Drawstring closure prevents spills",
      "Stiff rim keeps the bag open for easy hand entry",
      "Brush holder loop on side",
      "Belt loop and clip-in carabiner included",
      "Three color options"],
     {"Capacity": "Fits up to 100g of chalk", "Material": "Cordura nylon exterior, fleece interior",
      "Closure": "Drawstring", "Belt Loop": "Yes", "Carabiner Clip": "Included",
      "Brush Holder": "Yes (side webbing loop)", "Color Options": "Black, Blue, Orange",
      "Weight": "85 g"},
     [("Does it come with chalk?", "No — chalk is sold separately. The bag accommodates loose chalk, chalk balls, or block chalk."),
      ("Is the chalk dust-tight?", "The drawstring reduces spills but is not airtight; some dust may escape during transport.")],
     "1-year limited warranty against stitching and zipper defects. Non-transferable."),

    (26, "SteelLock Carabiner Set", 60, "AlpineEdge", "Climbing Hardware",
     ["Six-pack of locking carabiners for anchors and belay",
      "Screw-gate locking mechanism",
      "Forged aluminum alloy for high strength-to-weight ratio",
      "Smooth gate action with anti-cross-load design",
      "Color-coded for easy identification at the anchor",
      "CE and UIAA certified"],
     {"Type": "Locking carabiner (screw gate)", "Quantity": "6",
      "Major Axis Strength": "25 kN", "Minor Axis Strength": "8 kN",
      "Open Gate Strength": "8 kN", "Material": "7075-T6 aluminum",
      "Weight per Carabiner": "70 g", "Gate Opening": "21 mm",
      "Colors": "Mixed (red, blue, green, gold, silver, black)",
      "Certifications": "UIAA, CE EN 12275"},
     [("Are these auto-locking?", "No — these are screw-gate. Auto-locking variants are available separately for higher-consequence applications."),
      ("Can I use them for top-rope anchors?", "Yes — the 25 kN major axis strength is well within safe parameters for top-rope anchor systems.")],
     "Lifetime warranty against manufacturing defects in the metal forging. Retire after major fall or visible deformation. Non-transferable."),

    (27, "QuickClip Quickdraws", 90, "AlpineEdge", "Climbing Hardware",
     ["Six-pack of pre-rigged quickdraws for sport climbing",
      "Wire-gate top carabiner reduces accidental gate flutter",
      "Solid-gate bottom carabiner with deep keylock nose",
      "Reinforced dyneema dogbone resists abrasion",
      "Bottom carabiner has rope-end indicator stripe",
      "Available in 12cm and 17cm dogbone lengths"],
     {"Quantity": "6 quickdraws", "Top Carabiner": "Wire-gate, 23 kN major axis",
      "Bottom Carabiner": "Solid-gate keylock, 24 kN major axis",
      "Dogbone Material": "12 mm Dyneema", "Dogbone Length": "12 cm (also available in 17 cm)",
      "Weight per Quickdraw": "92 g", "Total Weight": "552 g",
      "Certifications": "UIAA, CE EN 12275"},
     [("Should I use the wire-gate at the top or bottom?", "Wire-gate at the bolt (top) — reduced gate flutter prevents accidental unclipping during dynamic falls."),
      ("Can I extend these with a sling?", "Yes — the wire-gate can be clipped through any sewn sling for extension, useful for trad placements.")],
     "Lifetime warranty against manufacturing defects. Inspect dogbone webbing regularly for fraying. Non-transferable."),

    (28, "BelayPro Belay Device", 40, "GripWorks", "Climbing Hardware",
     ["Tube-style belay device for single and double ropes",
      "Compatible with rope diameters from 8.5mm to 11mm",
      "Grooved friction surfaces enhance control during lowers",
      "Lightweight aluminum construction",
      "Suitable for top-rope, lead, and rappelling",
      "Wire keeper attaches to harness belay loop"],
     {"Type": "Tubular belay device (ATC-style)",
      "Rope Compatibility": "8.5-11 mm single, 7.5-9 mm double/twin",
      "Material": "Anodized aluminum", "Weight": "65 g",
      "Modes": "Top-rope, lead belay, rappel",
      "Color": "Black with red friction grooves",
      "Certifications": "CE EN 15151-2"},
     [("Is this an assisted-braking device?", "No — this is a manual tube-style device. Assisted-braking devices like the GriGri are sold separately."),
      ("Can I rappel double-rope with this?", "Yes — the device accommodates two ropes simultaneously for retrievable rappels.")],
     "1-year limited warranty against manufacturing defects. Inspect for grooving and burrs after heavy use. Non-transferable."),

    (29, "AlpineEdge Bouldering Crash Pad", 250, "AlpineEdge", "Bouldering Pad",
     ["Closed-cell and open-cell foam sandwich for impact distribution",
      "Hinge-style fold (not taco) for clean closure over gear",
      "Reinforced corners resist abrasion",
      "Dual shoulder straps with sternum and hip belt for hauling",
      "Carpet shoe-wiping zone on top surface",
      "Velcro flap connects multiple pads for landing zone coverage",
      "Cleanable cordura nylon top surface"],
     {"Type": "Hinge-style (not taco-fold)",
      "Open Dimensions": "48 in x 36 in x 4 in",
      "Closed Dimensions": "36 in x 24 in x 8 in",
      "Foam Construction": "1 in closed-cell over 3 in open-cell",
      "Weight": "11 lbs", "Carry System": "Backpack-style with hip belt",
      "Cover Material": "1000D Cordura nylon", "Color": "Forest Green/Black"},
     [("Will one pad cover most highball boulders?", "For taller boulders, climbers typically combine 2-3 pads to cover the full landing zone."),
      ("Can I use this for trail running impact training?", "Designed specifically for bouldering falls; not ideal for repeated jump training.")],
     "2-year limited warranty against manufacturing defects in stitching and foam delamination. Does not cover punctures or wear from rocks. Non-transferable."),

    (30, "GripGuard Climbing Tape", 15, "GripWorks", "Climbing Accessories",
     ["Three-pack of athletic tape rolls for finger and hand support",
      "Hypoallergenic adhesive suitable for sensitive skin",
      "Tears cleanly by hand — no scissors required",
      "Breathable cotton-rayon blend",
      "Available in white, black, and colored",
      "1.5 inch width fits most climbing applications"],
     {"Quantity": "3 rolls", "Width": "1.5 in", "Length per Roll": "10 yards",
      "Material": "Cotton-rayon blend with zinc oxide adhesive",
      "Tear-by-hand": "Yes", "Hypoallergenic": "Yes",
      "Total Length (3 rolls)": "30 yards", "Color": "White (default)"},
     [("How long does taped skin last between climbs?", "A proper tape job typically lasts a single climbing session; replace as the adhesive weakens."),
      ("Can I use this for medical first aid?", "Yes — the cotton-rayon blend and zinc oxide adhesive are equivalent to standard athletic tape used in sports medicine.")],
     "No warranty (consumable product). Replace after each use."),

    # ---------- WATER SPORTS (31-40) ----------
    (31, "RiverGlide Kayak Paddle", 130, "AquaTrek", "Kayak Paddle",
     ["Two-piece adjustable shaft for transport and storage",
      "Reinforced fiberglass blades for stiffness",
      "Carbon-reinforced shaft reduces fatigue on long paddles",
      "Adjustable feathering angle (0°, 45°, 60°)",
      "Drip rings keep water off your hands",
      "Suitable for recreational and touring kayaks",
      "Length adjustable from 220cm to 240cm"],
     {"Length": "220-240 cm adjustable",
      "Blade Material": "Reinforced fiberglass",
      "Shaft Material": "Carbon-fiber reinforced fiberglass",
      "Weight": "880 g", "Feathering Angles": "0°, 45°, 60° (left or right)",
      "Blade Surface Area": "640 sq cm", "Drip Rings": "Included",
      "Color": "Yellow blades, black shaft"},
     [("Can I use this for whitewater?", "This paddle is designed for flat water and mild current. Whitewater paddles have a shorter length and reinforced blades."),
      ("How do I choose the right length?", "For flat-water paddling, use a length 25-30 cm longer than your height; for narrower boats, shorter is better.")],
     "2-year limited warranty against manufacturing defects in the shaft and blade joints. Does not cover impact damage. Non-transferable."),

    (32, "SafeFloat Life Vest", 95, "AquaTrek", "Personal Flotation Device",
     ["US Coast Guard approved Type III PFD",
      "Three large front pockets for organizing safety gear",
      "Reflective trim and signal whistle attached",
      "Mesh ventilation panels reduce heat buildup",
      "Adjustable side and shoulder straps for custom fit",
      "Available in three sizes: M, L, XL"],
     {"Type": "USCG Type III", "Buoyancy": "16.5 lbs (74 N)",
      "Outer Material": "200D nylon ripstop", "Inner Foam": "PE foam",
      "Closure": "Front zipper with three side adjustment straps",
      "Pockets": "3 zippered front pockets", "Reflective Trim": "Yes",
      "Whistle": "Attached safety whistle", "Sizes": "M (chest 36-40 in), L (40-44 in), XL (44-48 in)",
      "Color": "Safety Orange"},
     [("Is this approved for whitewater?", "Type III is approved for general boating and calm water. For whitewater, use a Type V high-buoyancy vest."),
      ("How often should I replace the vest?", "Inspect annually; replace if foam shows compression, fabric is faded by UV exposure, or stitching is damaged.")],
     "1-year warranty on stitching and zipper hardware. Foam buoyancy is warranted for life of the product when properly stored. Non-transferable."),

    (33, "DryShield Waterproof Bag", 55, "AquaTrek", "Dry Bag",
     ["30-liter capacity for multi-day trips",
      "Roll-top closure with side-release buckle",
      "Welded seams (not stitched) for true waterproof rating",
      "Removable shoulder strap for portage",
      "Clear inspection window on side",
      "Air purge valve for compression",
      "Available in 10L, 20L, 30L, and 60L"],
     {"Capacity": "30 L", "Material": "500D PVC-coated polyester",
      "Waterproof Rating": "IPX7 (submersion to 1m for 30 min)",
      "Closure": "Triple-fold roll-top with buckle",
      "Seams": "RF-welded (waterproof)",
      "Carry Options": "Removable shoulder strap, top handle",
      "Weight (empty)": "560 g", "Color Options": "Yellow, Blue, Black, Orange"},
     [("Will this float if I drop it in the water?", "Yes — when properly sealed with the roll-top, the bag traps air and floats."),
      ("Can I submerge it for long periods?", "IPX7 rating supports 30 minutes of submersion in 1 meter of water. For longer or deeper, use a dry box.")],
     "Lifetime warranty against seam failure under normal use. Does not cover punctures or buckle damage from misuse. Non-transferable."),

    (34, "SeaScout Inflatable Kayak", 450, "AquaTrek", "Kayak",
     ["Two-person inflatable kayak with high-pressure floor",
      "Three-chamber design for safety redundancy",
      "Drop-stitch floor provides rigid paddling platform",
      "Includes high-pressure pump, repair kit, and carrying bag",
      "Sets up in 10 minutes with no tools",
      "Multiple D-rings for gear attachment"],
     {"Capacity": "2 adults (550 lbs)", "Length Inflated": "12 ft 6 in",
      "Width Inflated": "37 in", "Material": "1000D PVC tarpaulin",
      "Number of Air Chambers": "3", "Inflation Pressure": "0.18 bar (main), 0.7 bar (drop-stitch floor)",
      "Weight (deflated)": "37 lbs", "Includes": "Hand pump, repair kit, carry bag, two seats",
      "Setup Time": "Approximately 10 minutes",
      "Best Use": "Lakes, slow rivers, calm coastal waters"},
     [("Can I use this in the ocean?", "Designed for protected coastal water (bays, lagoons). Not recommended for open ocean or rough surf."),
      ("How durable is the PVC?", "1000D material resists most punctures from ordinary debris but can be damaged by sharp rocks or deliberate cuts; carry the included repair kit.")],
     "2-year limited warranty against manufacturing defects in seams and air chambers. Does not cover punctures or UV degradation. Non-transferable."),

    (35, "WaveRider SUP Board", 550, "AquaTrek", "Stand-Up Paddleboard",
     ["Inflatable stand-up paddleboard with high-pressure drop-stitch construction",
      "Bungee tie-down system for gear",
      "Removable center fin for tracking",
      "Includes paddle, pump, leash, fin, and travel backpack",
      "Reinforced rails resist abrasion against rocks",
      "Suitable for flat water, light surf, and yoga"],
     {"Length": "10 ft 6 in", "Width": "32 in", "Thickness": "6 in",
      "Volume": "270 L", "Max Weight": "300 lbs",
      "Material": "Drop-stitch core with 1000D PVC outer",
      "Inflation Pressure": "Up to 18 PSI", "Weight (deflated)": "21 lbs",
      "Includes": "Adjustable paddle, pump, removable fin, ankle leash, backpack",
      "Best Use": "Flat water, mild surf, SUP yoga"},
     [("How long does it take to inflate?", "About 8-10 minutes by hand pump to reach 15 PSI. Electric pumps reduce this to 5 minutes."),
      ("Is this rigid enough for adults?", "Yes — at 18 PSI the drop-stitch construction is comparable to a rigid board for paddler stability.")],
     "2-year limited warranty against seam failure and drop-stitch separation. Does not cover punctures, UV damage, or abrasion. Non-transferable."),

    (36, "AquaLite Swim Goggles", 35, "AquaTrek", "Swim Accessory",
     ["Anti-fog UV-protective lenses",
      "Soft silicone gasket for leak-free seal",
      "Quick-adjust split strap for secure fit",
      "Polycarbonate lens resists scratches",
      "Mirrored coating reduces glare for outdoor swimming",
      "Carrying case included"],
     {"Lens Material": "Polycarbonate with anti-fog and UV coating",
      "Gasket Material": "Hypoallergenic silicone",
      "Strap": "Adjustable split silicone strap",
      "Lens Tint": "Mirrored blue (also available in clear and amber)",
      "UV Protection": "100% UVA/UVB",
      "Best Use": "Pool, open water, triathlon",
      "Includes": "Hard-shell carrying case",
      "Color Options": "Blue mirror, Clear, Amber"},
     [("Will these fit children?", "These are sized for adults. A youth model is sold separately for ages 6-14."),
      ("How do I prevent fogging?", "Pre-rinse before each use and avoid touching the inside of the lenses. The anti-fog coating typically lasts 6-12 months with proper care.")],
     "6-month limited warranty against gasket and strap defects. Lens scratches and anti-fog wear are not covered. Non-transferable."),

    (37, "SplashGuard Dry Top", 120, "AquaTrek", "Paddling Apparel",
     ["Waterproof breathable shell for paddling and kayaking",
      "Latex neck and wrist gaskets seal out water",
      "Adjustable hem with bungee cord",
      "Reinforced seat and elbow areas",
      "Three-layer construction balances waterproofing and breathability",
      "Available in S, M, L, XL"],
     {"Outer Shell": "3-layer nylon with PU coating",
      "Waterproof Rating": "20,000 mm",
      "Breathability": "15,000 g/m²/24h",
      "Neck Gasket": "Latex (replaceable)",
      "Wrist Gaskets": "Latex (replaceable)",
      "Hem": "Adjustable bungee with cord lock",
      "Pockets": "1 chest pocket (waterproof zip)",
      "Sizes": "S, M, L, XL",
      "Color": "Charcoal/Yellow"},
     [("Will the latex gaskets degrade?", "Yes — latex degrades from sun exposure, ozone, and skin oils; expect to replace gaskets every 1-2 seasons of regular use."),
      ("Can I wear this for whitewater?", "Yes — for serious whitewater, pair with a dry suit or splash bib for full lower-body coverage.")],
     "1-year limited warranty against shell delamination and seam failure. Latex gaskets are wear items and not covered. Non-transferable."),

    (38, "RiverGlide Spray Skirt", 80, "AquaTrek", "Kayak Accessory",
     ["Neoprene spray skirt for sit-inside kayaks",
      "Adjustable bungee rim grips most cockpit shapes",
      "Reinforced grab loop on front",
      "Suspender straps prevent skirt from falling",
      "Suitable for touring and recreational kayaks",
      "Available in three cockpit sizes"],
     {"Material": "3 mm neoprene tunnel and deck",
      "Cockpit Size Options": "Small (recreational), Medium, Large (touring)",
      "Tunnel Sizes": "S (28-34 in waist), M (34-40 in), L (40-46 in)",
      "Reinforcement": "1000D Cordura on rim and sit area",
      "Grab Loop": "Reinforced webbing with floating handle",
      "Color": "Black",
      "Best Use": "Touring and recreational kayaks"},
     [("Is this suitable for whitewater?", "Whitewater requires a tighter fit and stiffer construction; use a dedicated whitewater spray skirt for class III+ paddling."),
      ("How do I clean the neoprene?", "Rinse with fresh water after each use, drip-dry out of direct sunlight; occasional mild soap for stubborn stains.")],
     "1-year limited warranty against seam failure and bungee defects. Non-transferable."),

    (39, "AquaShield Waterproof Phone Case", 30, "AquaTrek", "Phone Case",
     ["IPX8-rated submersible phone case for water sports",
      "Touchscreen-compatible window works underwater",
      "Floats in water if dropped",
      "Universal fit for most phones up to 6.7 inches",
      "Lanyard included for around-the-neck use",
      "Camera lens window for clear photos"],
     {"Waterproof Rating": "IPX8 (continuous submersion to 30 m)",
      "Phone Compatibility": "Up to 6.7-inch screen size",
      "Material": "TPU with high-clarity windows",
      "Touch Sensitivity": "Yes (works underwater)",
      "Floats": "Yes (when sealed properly)",
      "Closure": "Triple-lock pressure seal with lanyard",
      "Includes": "Adjustable lanyard, microfiber cleaning cloth",
      "Color Options": "Black, Clear, Blue"},
     [("Will my phone work normally inside the case?", "Touchscreen, buttons, and camera all work. Speaker volume and microphone clarity may be slightly muffled."),
      ("Can I take it scuba diving?", "Rated to 30 m which covers recreational diving depths. Test with a tissue paper inside before submerging your phone.")],
     "30-day money-back guarantee. 6-month warranty against seal failures. Always test the seal before submerging your phone. Non-transferable."),

    (40, "FlowMaster River Shoes", 75, "AquaTrek", "Water Footwear",
     ["Quick-draining mesh upper",
      "Sticky rubber outsole grips wet rocks",
      "Toe protection bumper for river walking",
      "Adjustable bungee lacing",
      "Removable insole for cleaning",
      "Suitable for kayaking, rafting, and creek hiking"],
     {"Upper Material": "Quick-dry mesh with TPU overlay",
      "Outsole": "Sticky rubber compound (similar to climbing shoes)",
      "Closure": "Bungee with toggle lock",
      "Drainage": "Side and bottom drainage ports",
      "Insole": "Removable EVA",
      "Sizes": "US 5-13 (unisex)",
      "Color": "Slate Grey",
      "Weight per Pair": "550 g (size 9)"},
     [("Are these good for swimming?", "They function while swimming but are designed for river walking and kayaking, not for lap swimming."),
      ("How do they dry?", "Mesh upper drains and air-dries within 1-2 hours in moderate weather; full sun accelerates drying.")],
     "1-year limited warranty against outsole separation and seam failure. Does not cover normal sole wear. Non-transferable."),

    # ---------- WINTER SPORTS (41-50) ----------
    (41, "SnowTrek Snowshoes", 175, "FrostGear", "Snowshoes",
     ["Aggressive crampon design for steep winter terrain",
      "Heel lift bar for ascending steep slopes",
      "Quick-pull binding accommodates winter boots",
      "Aluminum frame for lightweight strength",
      "Tail extensions sold separately for deeper snow",
      "Available in 25-inch and 30-inch lengths"],
     {"Length": "25 in (also available in 30 in)",
      "Recommended Weight": "Up to 220 lbs (with gear)",
      "Frame Material": "6061 aluminum",
      "Decking": "TPE-coated polyester",
      "Bindings": "Quick-pull ratchet straps",
      "Crampons": "Stainless steel with toe and heel claws",
      "Heel Lift Bar": "Yes",
      "Weight per Pair": "4.4 lbs",
      "Color": "Black/Lime"},
     [("Are these suitable for icy slopes?", "The stainless steel crampons grip well on packed snow and light ice. For glacier travel or hard ice, mountaineering crampons are required."),
      ("Can I use them with hiking boots?", "Yes — the binding fits most insulated winter boots and many three-season hiking boots.")],
     "2-year limited warranty against frame and crampon defects. Bindings are warranted for 1 year. Non-transferable."),

    (42, "IceClimb Ice Axe", 120, "FrostGear", "Ice Climbing Tool",
     ["General-mountaineering ice axe for glacier travel and steep snow",
      "Curved aluminum shaft for self-arrest leverage",
      "Steel pick with aggressive teeth",
      "Adze and spike both made of carbon steel",
      "Rubber grip with leash attachment loop",
      "Available in 60cm, 70cm, and 80cm lengths"],
     {"Length": "70 cm (also 60 cm and 80 cm)",
      "Weight": "490 g",
      "Pick Material": "Steel with carbide-coated teeth",
      "Shaft Material": "7075 aluminum",
      "Adze": "Carbon steel",
      "Spike": "Carbon steel",
      "Grip": "Rubber-coated with wrist leash slot",
      "Best Use": "Glacier travel, steep snow, general mountaineering",
      "Certifications": "UIAA, CE EN 13089"},
     [("Is this suitable for ice climbing?", "This is a general-purpose mountaineering axe. For vertical ice climbing, use a technical tool with a reverse-curve pick."),
      ("How do I size the axe?", "Hold the axe by the head with the spike pointing down; the spike should reach approximately your ankle bone for general mountaineering use.")],
     "Lifetime warranty against shaft and pick defects. Does not cover impact damage to the pick teeth from striking rock. Non-transferable."),

    (43, "AlpineEdge Crampons", 160, "AlpineEdge", "Crampons",
     ["12-point steel crampons for general mountaineering",
      "Adjustable horizontal length for boot compatibility",
      "Anti-balling plates prevent snow buildup",
      "Quick-fit binding works with stiff or semi-stiff boots",
      "Carrying bag and tool included",
      "Suitable for alpine climbing, glacier travel, and ice"],
     {"Type": "12-point general mountaineering",
      "Material": "Chrome-molybdenum steel",
      "Boot Compatibility": "Stiff or semi-stiff boots with welts",
      "Binding": "Strap-on with optional step-in for compatible boots",
      "Anti-balling Plates": "Polypropylene, included",
      "Adjustment Range": "EU 36-48",
      "Weight per Pair": "2.1 lbs",
      "Includes": "Carry bag, adjustment tool, anti-balling plates",
      "Certifications": "UIAA, CE EN 893"},
     [("Will these fit my flexible hiking boots?", "Crampons require boots stiff enough to support full-body weight on the front points. Use semi-stiff or B2-rated boots minimum."),
      ("Can I use them on mixed rock and ice?", "Yes — the steel construction handles mixed terrain. For pure rock approaches, remove crampons.")],
     "2-year limited warranty against frame defects and binding hardware. Front-point wear is not covered. Non-transferable."),

    (44, "WinterPeak Insulated Boots", 220, "FrostGear", "Winter Boots",
     ["Waterproof leather upper with insulated lining",
      "200g Thinsulate insulation for cold-weather warmth",
      "Aggressive tread for snow and ice traction",
      "Removable thermal insole",
      "Lace-to-toe construction for secure fit",
      "Crampon-compatible welt"],
     {"Insulation": "200g Thinsulate Ultra",
      "Upper": "Waterproof full-grain leather",
      "Membrane": "Waterproof breathable",
      "Outsole": "Vibram with self-cleaning lugs",
      "Insole": "Removable thermal-reflective",
      "Welts": "Heel welt only (B1 crampon-compatible)",
      "Comfort Range": "Down to -25°F",
      "Sizes": "US 7-13 (men), US 6-12 (women)",
      "Weight per Boot": "1100 g",
      "Color": "Espresso Brown"},
     [("Are these suitable for technical mountaineering?", "B1 welt supports strap-on crampons for general mountaineering. For technical alpine routes, use full B2 or B3 boots."),
      ("How do I break them in?", "Wear around the house and on short walks for 5-10 hours before extended use. Leather softens over time.")],
     "2-year warranty against waterproof membrane failure and seam separation. Outsole wear is not covered. Non-transferable."),

    (45, "SnowGuard Gaiters", 45, "FrostGear", "Gaiters",
     ["Tall waterproof gaiters for snow protection",
      "Reinforced bottom strap resists abrasion",
      "Front zip with hook-and-loop storm flap",
      "Adjustable top closure",
      "Reflective trim for visibility",
      "Available in S/M, L/XL"],
     {"Height": "16 in (knee height)",
      "Material": "Waterproof breathable nylon ripstop",
      "Bottom Strap": "Replaceable rubber strap",
      "Front Closure": "YKK water-resistant zipper with storm flap",
      "Top Closure": "Hook-and-loop with elastic cuff",
      "Sizes": "S/M (boot 7-9.5), L/XL (boot 10-13)",
      "Color": "Black with reflective grey trim",
      "Weight per Pair": "260 g"},
     [("Will these work with mountaineering boots?", "Yes — the bottom strap accommodates most mountaineering and ski boot soles."),
      ("Are they fully waterproof?", "Yes — taped seams and water-resistant zipper provide full waterproofing for snow and brief water immersion.")],
     "1-year limited warranty against seam failure and zipper defects. Replacement straps available separately. Non-transferable."),

    (46, "PowderPro Ski Poles", 90, "FrostGear", "Ski Poles",
     ["Adjustable backcountry ski poles",
      "Aluminum upper, fiberglass lower for shock absorption",
      "Powder baskets and replaceable trekking baskets",
      "Foam grip with adjustable strap",
      "Length adjustable from 105cm to 145cm",
      "Two-section quick-lock telescoping design"],
     {"Length Range": "105-145 cm adjustable",
      "Sections": "2-piece telescoping",
      "Lock System": "External quick-lock lever",
      "Upper Shaft": "7075 aluminum",
      "Lower Shaft": "Fiberglass composite",
      "Grip": "EVA foam with strap",
      "Baskets": "Powder basket (4 in) and trekking basket (2 in) — both included",
      "Weight per Pair": "560 g",
      "Color": "Volcanic Red/Black"},
     [("Are these suitable for cross-country skiing?", "These are designed for backcountry skiing and snowshoeing. XC poles are typically longer and lighter."),
      ("Can I use them for trekking in summer?", "Yes — swap to the included trekking baskets for three-season hiking use.")],
     "2-year limited warranty against shaft and lock defects. Baskets and grips are wear items. Non-transferable."),

    (47, "ArcticShield Down Jacket", 280, "FrostGear", "Insulated Jacket",
     ["800-fill power down for ultralight warmth",
      "DWR-treated nylon shell sheds light snow and rain",
      "Hood fits over a helmet",
      "Two zippered hand pockets and one chest pocket",
      "Drawcord hem for sealing in heat",
      "Compresses to size of a 2-liter bottle"],
     {"Insulation": "800-fill power goose down (Responsible Down Standard certified)",
      "Shell Material": "20D ripstop nylon with DWR",
      "Lining": "20D ripstop nylon",
      "Pockets": "2 hand, 1 chest, 1 internal mesh dump pocket",
      "Hood": "Fixed, helmet-compatible with adjustable cinch",
      "Hem": "Adjustable drawcord",
      "Weight": "510 g (men's M)",
      "Comfort Range": "20°F to -10°F (active use, layered)",
      "Sizes": "S, M, L, XL",
      "Color": "Glacier Blue, Red, Black"},
     [("Is this jacket waterproof?", "The DWR coating sheds light snow and rain but the jacket is not waterproof. Pair with a hardshell for sustained precipitation."),
      ("How do I care for the down?", "Hand-wash with down-specific soap or take to a specialty cleaner. Tumble dry low with clean tennis balls to restore loft.")],
     "Lifetime warranty against manufacturing defects in stitching and zippers. Down loft is warranted for 5 years. Non-transferable."),

    (48, "ThermalCore Base Layer Set", 110, "FrostGear", "Base Layer",
     ["Merino wool base layer top and bottom",
      "Naturally odor-resistant — wear for multiple days",
      "Flatlock seams reduce chafing",
      "Thumb loops on top sleeves",
      "Available in lightweight and midweight",
      "S, M, L, XL"],
     {"Material": "100% merino wool, 18.5 micron",
      "Weight Class": "Midweight (200 g/m²)",
      "Top": "Long-sleeve crew neck with thumb loops",
      "Bottom": "Full-length leggings with elastic waist",
      "Stitching": "Flatlock seams",
      "Care": "Machine wash cold, lay flat to dry",
      "Sizes": "S, M, L, XL (unisex)",
      "Color": "Forest Green, Charcoal, Burgundy"},
     [("How does merino compare to synthetics?", "Merino is warmer when wet, naturally odor-resistant, and more comfortable against skin. Synthetics dry faster and are more durable."),
      ("Can I wear this as a single layer for running?", "The midweight is best as a base under additional layers in cold weather. For running, choose a lightweight version.")],
     "1-year limited warranty against seam failure and pilling beyond normal wear. Non-transferable."),

    (49, "AlpineDream Goggles", 95, "FrostGear", "Snow Goggles",
     ["Anti-fog double-pane lens",
      "100% UV protection",
      "Helmet-compatible strap with silicone grip",
      "Triple-layer face foam with moisture-wicking liner",
      "Wide field of vision",
      "Interchangeable lenses (sold separately)"],
     {"Lens Type": "Double-pane spherical with anti-fog treatment",
      "Lens Tint": "Pink mirror (VLT 25%)",
      "UV Protection": "100% UVA/UVB",
      "Frame Size": "Medium-large (fits most adult faces)",
      "Strap": "1.5 in silicone-backed",
      "Foam": "3-layer face foam with fleece liner",
      "Lens Interchange": "Quick-change magnetic system",
      "Helmet Compatibility": "Most snow helmets",
      "Sizes Available": "Medium-Large only (one size)",
      "Color": "Frame: Black, Strap: Pink/Black pattern"},
     [("Will these fit over my prescription glasses?", "These are not specifically OTG (over-the-glasses); for slim eyewear it may work, but dedicated OTG goggles are recommended for thicker frames."),
      ("How do I prevent fogging?", "Avoid wiping the inside of the double-pane lens. Allow goggles to ventilate when not in use; never store them in your jacket where moisture can build up.")],
     "1-year limited warranty against frame and lens defects. Lens scratches from improper cleaning are not covered. Non-transferable."),

    (50, "SnowPeak Backcountry Pack", 200, "FrostGear", "Backcountry Pack",
     ["35-liter capacity for day tours and overnight ski touring",
      "External ski and snowboard carry straps",
      "Avalanche tool pocket for shovel and probe",
      "Hydration reservoir compartment",
      "Reinforced bottom resists ski edge damage",
      "Hip belt with gear pockets",
      "Removable lid for weight savings"],
     {"Capacity": "35 L",
      "Material": "420D ripstop nylon with reinforced base",
      "Frame": "Internal HDPE sheet with aluminum stay",
      "Hydration Sleeve": "Yes (3 L compatible)",
      "Avalanche Pocket": "Dedicated front pocket for shovel and probe",
      "Ski Carry": "A-frame and diagonal carry options",
      "Hip Belt": "Padded with two zip pockets",
      "Lid": "Removable",
      "Weight": "1.4 kg",
      "Color": "Volcanic Red, Storm Grey"},
     [("Will this fit a full avalanche kit?", "Yes — the dedicated avalanche pocket fits a 30 cm shovel and 280 cm probe. Beacons go in a chest harness, sold separately."),
      ("Is this airbag-compatible?", "No — this is a standard backcountry pack. Airbag-equipped packs are sold as a separate model.")],
     "Lifetime warranty against material and stitching defects. Buckles and zippers warranted for 2 years. Non-transferable."),

    # ---------- FISHING (51-58) ----------
    (51, "RiverCast Fly Rod", 200, "AnglerPro", "Fly Rod",
     ["9-foot 5-weight fly rod for trout fishing",
      "Four-piece construction for travel",
      "IM7 graphite blank with fast action",
      "Cork grip with hidden reel seat insert",
      "Comes with rod tube and protective sock",
      "Lifetime warranty"],
     {"Length": "9 ft", "Line Weight": "5", "Action": "Fast",
      "Pieces": "4", "Material": "IM7 graphite",
      "Grip": "Half-wells cork", "Reel Seat": "Aluminum, hidden hood",
      "Includes": "Rigid rod tube, cloth sock", "Weight": "3.2 oz",
      "Best Use": "Trout, small bass, panfish", "Color": "Olive Green blank, brown wraps"},
     [("Can I use this for saltwater?", "5-weight is intended for freshwater; for inshore saltwater (bonefish, redfish), choose 8-weight or higher."),
      ("Is this good for beginners?", "Fast action requires good casting timing; intermediate anglers will get the most from this rod. Beginners may prefer medium-fast.")],
     "Lifetime warranty against blank breakage from manufacturing defects. Cosmetic damage and wear are not covered. Non-transferable."),

    (52, "AnglerPro Tackle Box", 40, "AnglerPro", "Tackle Storage",
     ["Three-tray hard-shell tackle box",
      "Adjustable dividers for custom organization",
      "Top tray flips up for hook-free access",
      "Latching lid keeps tackle secure",
      "Carry handle and shoulder strap",
      "Weather-resistant seal"],
     {"Material": "Impact-resistant polypropylene",
      "Trays": "3 (lift-up cantilever style)",
      "Dividers": "Adjustable plastic dividers",
      "Latches": "2 spring-loaded plastic",
      "Carry": "Handle and removable shoulder strap",
      "Dimensions": "16 in x 9 in x 9 in",
      "Weight (empty)": "1.8 lbs",
      "Color": "Forest Green"},
     [("Will this fit in a kayak storage compartment?", "16 in length fits most kayak day hatches. Measure your hatch dimensions before ordering."),
      ("Are the dividers removable?", "Yes — the plastic dividers slide out and can be repositioned in any of the molded slots.")],
     "1-year warranty against latch failure and crack defects. Non-transferable."),

    (53, "WaderFlex Chest Waders", 190, "AnglerPro", "Fishing Waders",
     ["Stockingfoot chest waders for fly fishing",
      "Three-layer breathable nylon construction",
      "Adjustable suspenders and wading belt",
      "Two zippered chest pockets",
      "Reinforced knees and seat",
      "Available in S, M, L, XL, XXL"],
     {"Type": "Stockingfoot (boots sold separately)",
      "Material": "3-layer breathable nylon",
      "Waterproof Rating": "20,000 mm",
      "Bootie Material": "Neoprene with fleece lining",
      "Chest Pockets": "2 zippered (1 fleece-lined)",
      "Suspenders": "Y-back adjustable",
      "Belt": "Included quick-release belt",
      "Sizes": "S, M, L, XL, XXL",
      "Color": "Stone Grey",
      "Weight": "1.6 kg"},
     [("Why stockingfoot vs. bootfoot?", "Stockingfoot allows you to choose dedicated wading boots with appropriate sole (felt or studded rubber) for the river substrate."),
      ("How do I prevent leaks?", "Avoid sitting on rough surfaces, store hung up (not folded), and patch small holes immediately with the included repair patch.")],
     "1-year limited warranty against seam failure and material defects. Punctures and abrasion damage are not covered. Non-transferable."),

    (54, "SonarFinder Portable Fish Finder", 250, "AnglerPro", "Electronics",
     ["Wireless castable sonar with smartphone app",
      "Maps depth and structure up to 130 feet",
      "Castable from kayak, boat, or shore",
      "Rechargeable battery — 10 hours per charge",
      "GPS tagging of fish marks",
      "Compatible with iOS and Android"],
     {"Sonar Range": "130 ft depth, 65 ft horizontal",
      "Frequency": "Dual frequency (290 kHz / 90 kHz)",
      "Battery": "Rechargeable lithium, 10-hour runtime",
      "Connection": "Bluetooth and Wi-Fi to smartphone",
      "App Compatibility": "iOS 13+, Android 9+",
      "GPS": "Integrated for waypoint tagging",
      "Cast Distance": "Up to 200 ft",
      "Weight": "100 g",
      "Includes": "Sonar puck, USB-C charger, soft case",
      "Color": "Volcanic Orange"},
     [("Does it work in saltwater?", "Yes — the puck is fully waterproof and rated for both fresh and saltwater use. Rinse with fresh water after saltwater use."),
      ("Can I use it without a smartphone?", "No — display is via the smartphone app. The sonar puck has no built-in screen.")],
     "1-year limited warranty against electronic and battery defects. Battery capacity is warranted to 80% of original after 1 year. Non-transferable."),

    (55, "LureMaster Trout Lure Kit", 35, "AnglerPro", "Fishing Lures",
     ["20-piece assortment of trout lures",
      "Includes spoons, spinners, and crankbaits",
      "Pre-rigged with hooks ready to fish",
      "Plastic carrying tray with sorted compartments",
      "Mix of natural and bright color patterns",
      "Suitable for stream and lake trout"],
     {"Quantity": "20 lures",
      "Types": "8 spoons, 8 spinners, 4 crankbaits",
      "Weight Range": "1/16 oz to 1/4 oz",
      "Hook Sizes": "Sizes 8-12",
      "Materials": "Stainless steel hooks, brass and copper bodies",
      "Storage": "Compartmentalized plastic tray",
      "Best Use": "Trout in streams and small lakes",
      "Color Variety": "Natural (brown trout, rainbow patterns), bright (chartreuse, hot pink, copper)"},
     [("Are these suitable for catch-and-release?", "Yes — replace standard hooks with barbless hooks (sold separately) for easier release."),
      ("Will these work for steelhead?", "These are sized for trout. Steelhead require larger spinners (1/4 oz to 3/8 oz) and reinforced hooks.")],
     "30-day satisfaction guarantee. No warranty on hooks or lure bodies as these are wear items. Non-transferable."),

    (56, "ReelStrong Fishing Reel", 135, "AnglerPro", "Fishing Reel",
     ["Spinning reel for medium freshwater fishing",
      "10+1 stainless steel ball bearings for smooth retrieve",
      "Carbon fiber drag system rated to 22 lbs",
      "Aluminum body and rotor for strength and weight balance",
      "Quick-lock spool for fast line changes",
      "Suitable for bass, walleye, and trout"],
     {"Type": "Spinning reel",
      "Size": "3000 series",
      "Gear Ratio": "5.2:1",
      "Bearings": "10+1 stainless steel",
      "Drag System": "Carbon fiber",
      "Maximum Drag": "22 lbs",
      "Line Capacity": "150 yds of 10 lb monofilament",
      "Body Material": "Aluminum",
      "Weight": "9.2 oz",
      "Best Use": "Bass, walleye, trout, light inshore",
      "Color": "Black with red accents"},
     [("Is this saltwater-rated?", "The 3000 size is suitable for light inshore saltwater (small redfish, sea trout). Rinse thoroughly with fresh water after each saltwater use."),
      ("How do I maintain the drag?", "Loosen the drag fully when storing the reel. Replace the carbon fiber washers every 2-3 years of regular use.")],
     "5-year limited warranty against gear and frame defects. Bearings and drag washers are wear items. Non-transferable."),

    (57, "LineLast Braided Fishing Line", 20, "AnglerPro", "Fishing Line",
     ["20 lb test braided line",
      "300-yard spool fits most freshwater reels",
      "Low memory, knots well",
      "Color-fast dye resists fading",
      "Smaller diameter than monofilament for equivalent strength",
      "Available in 10-65 lb test"],
     {"Type": "Braided polyethylene",
      "Strength": "20 lb test",
      "Diameter": "0.23 mm (8 lb mono equivalent)",
      "Length": "300 yards",
      "Color": "Moss Green",
      "Stretch": "<5% (low stretch)",
      "Knot Strength": "98% (Palomar knot)",
      "Available Test Strengths": "10, 15, 20, 30, 50, 65 lb"},
     [("Should I use a fluorocarbon leader?", "Yes — for clear water and line-shy species, a 3-5 ft fluorocarbon leader (8-12 lb) reduces visibility."),
      ("Will it cut into my reel spool?", "Bury 8-10 wraps of monofilament backing first; braid alone can slip on the bare spool.")],
     "No warranty on line (consumable). 30-day satisfaction guarantee on first spool. Non-transferable."),

    (58, "AnglerPro Fishing Vest", 65, "AnglerPro", "Fishing Apparel",
     ["Multi-pocket fishing vest with 18 pockets",
      "Mesh back panel for ventilation",
      "D-rings for tools and net",
      "Adjustable side cinches for custom fit",
      "Reflective patches for visibility",
      "Available in S/M, L/XL, XXL"],
     {"Pockets": "18 (12 zippered, 4 mesh, 2 large back)",
      "Material": "Quick-dry polyester ripstop with mesh back",
      "D-rings": "4 (front and back)",
      "Adjustable": "Side cinch straps",
      "Reflective Trim": "Yes",
      "Sizes": "S/M (chest 36-42), L/XL (42-48), XXL (48-54)",
      "Weight": "550 g",
      "Color": "Sand"},
     [("Can I attach a wading staff?", "Yes — the rear D-ring is rated for a wading staff retractor and net."),
      ("Is the back panel insulated?", "No — the mesh back is designed for ventilation. For cold-weather fishing, layer over an insulating top.")],
     "1-year limited warranty against zipper and seam failure. Non-transferable."),

    # ---------- COOKING (59-66) ----------
    (59, "TrailChef Stainless Cookware Set", 80, "TrailChef", "Cookware",
     ["Four-piece stainless steel cookware set for camp kitchens",
      "Includes pot, pan, lid, and folding handle",
      "Stainless steel resists scratches and corrosion",
      "Lid doubles as a small pan",
      "Stackable for compact storage",
      "Mesh storage bag included"],
     {"Material": "18/8 stainless steel",
      "Pot Capacity": "1.5 L",
      "Pan Diameter": "20 cm",
      "Lid": "Doubles as 18 cm pan",
      "Handle": "Folding silicone-grip aluminum",
      "Total Weight": "780 g",
      "Pieces": "4 (pot, pan, lid, handle)",
      "Storage": "Mesh stuff sack included",
      "Stove Compatibility": "All (gas, induction, open fire)",
      "Color": "Mirror-polished steel"},
     [("Will this work on an induction stove?", "Yes — 18/8 stainless steel is induction-compatible. It also works on gas, electric, alcohol, and open flame."),
      ("How do I clean burnt-on food?", "Soak in hot soapy water, then scrub with stainless steel-safe pad. Avoid steel wool, which can scratch the polish.")],
     "Limited lifetime warranty against material and welding defects. Cosmetic scratches and discoloration not covered. Non-transferable."),

    (60, "AquaPure Water Filter Pump", 85, "TrailChef", "Water Filtration",
     ["Hand-pump water filter for backcountry use",
      "Filters bacteria and protozoa to 0.2 micron",
      "1 liter per minute pump rate",
      "Field-cleanable ceramic filter element",
      "Replaceable filter rated for 2,000 liters",
      "Compatible with most hydration bladders"],
     {"Filter Type": "Ceramic with carbon core",
      "Filtration Level": "0.2 micron (bacteria and protozoa)",
      "Pump Rate": "1 L/min",
      "Filter Lifespan": "Up to 2,000 L (variable by water quality)",
      "Output": "Standard hose with hydration adapter",
      "Weight": "350 g",
      "Includes": "Pump, intake float, output hose, prefilter, cleaning brush",
      "Best Use": "Backpacking, ultralight travel, emergency preparedness",
      "Color": "Volcanic Orange"},
     [("Does this filter viruses?", "No — viruses (e.g., norovirus) are smaller than 0.2 micron. For virus protection, add chemical or UV treatment."),
      ("How do I clean a clogged filter?", "Backflush with clean water; if performance doesn't recover, scrub the ceramic element with the included brush.")],
     "2-year limited warranty against pump and housing defects. Filter is a consumable item not covered by warranty. Non-transferable."),

    (61, "MessKit Pro Cookset", 45, "TrailChef", "Cookware",
     ["Lightweight aluminum mess kit",
      "Pot, pan, plate, mug, and utensils",
      "Anodized non-stick interior",
      "Nest together for compact carry",
      "Mesh bag included",
      "Suitable for solo backpacking"],
     {"Material": "Anodized aluminum",
      "Pot Capacity": "0.8 L",
      "Pan Diameter": "16 cm",
      "Plate": "20 cm aluminum",
      "Mug": "350 ml insulated",
      "Utensils": "Folding spoon, fork, knife (titanium)",
      "Total Weight": "420 g",
      "Pieces": "8",
      "Storage": "Mesh stuff sack",
      "Color": "Volcanic Black"},
     [("Is the non-stick coating PFOA-free?", "Yes — the anodized hard coat does not contain PFOA or PTFE."),
      ("Can I use metal utensils?", "Use only the included titanium utensils or wooden/silicone equivalents to preserve the anodized coating.")],
     "1-year limited warranty against material defects. Non-stick wear is normal and not covered. Non-transferable."),

    (62, "BearVault Food Storage Canister", 90, "TrailChef", "Food Storage",
     ["IGBC-certified bear-resistant canister",
      "11.5-liter capacity (5-7 days food for one person)",
      "Threaded lid requires a coin to open",
      "Transparent body for visual inventory",
      "Lightweight polycarbonate construction",
      "Fits in most backpacks"],
     {"Capacity": "11.5 L",
      "Capacity (food days)": "5-7 days for one person",
      "Material": "Transparent polycarbonate",
      "Closure": "Threaded lid (requires coin or thumbnail)",
      "Bear Certification": "IGBC (Interagency Grizzly Bear Committee) certified",
      "Weight": "2.4 lbs",
      "Dimensions": "12 in tall x 8.7 in diameter",
      "Color": "Transparent yellow-tinted"},
     [("Is this required in national parks?", "Yes — many parks (Yosemite, Sequoia, Glacier) require IGBC-certified canisters. Check park regulations before your trip."),
      ("Will it fit in my backpack?", "8.7 in diameter fits most 50L+ packs. For smaller packs, consider strapping it to the outside.")],
     "Lifetime warranty against canister body cracks. Lid threads warranted for 5 years. Non-transferable."),

    (63, "FlameMaster Fuel Canister", 30, "TrailChef", "Fuel",
     ["Four-pack of isobutane/propane fuel canisters",
      "230g each — approximately 90 minutes of burn time",
      "Compatible with most canister-top backpacking stoves",
      "Self-sealing valve",
      "Recyclable when fully empty",
      "Cold-weather optimized fuel blend"],
     {"Quantity": "4 canisters",
      "Fuel Mix": "80% isobutane, 20% propane",
      "Net Weight per Canister": "230 g",
      "Burn Time per Canister": "Approximately 90 minutes (full output)",
      "Valve Type": "Standard EN417 self-sealing",
      "Operating Temperature": "Down to 14°F",
      "Compatibility": "Most canister-top backpacking stoves",
      "Color": "Volcanic Red label"},
     [("Can I bring these on an airplane?", "No — pressurized fuel canisters are prohibited in checked and carry-on baggage. Buy fuel at your destination."),
      ("How do I dispose of empty canisters?", "Use a fuel canister recycling tool (sold separately) to puncture the canister fully empty, then recycle as scrap metal.")],
     "30-day satisfaction guarantee on full canisters. No warranty on consumed fuel. Non-transferable."),

    (64, "FlexBowl Collapsible Bowls", 25, "TrailChef", "Tableware",
     ["Four-pack of silicone collapsible bowls",
      "Compress to 0.5 inch thick when not in use",
      "Heat-resistant to 450°F",
      "Dishwasher and microwave safe",
      "Rigid rim provides stable shape",
      "Mixed colors for personal identification"],
     {"Quantity": "4 bowls",
      "Capacity per Bowl": "16 oz",
      "Material": "Food-grade silicone with rigid plastic rim",
      "Collapsed Thickness": "0.5 in",
      "Expanded Height": "2.5 in",
      "Diameter": "5.5 in",
      "Heat Resistance": "Up to 450°F",
      "Dishwasher Safe": "Yes (top rack)",
      "Microwave Safe": "Yes",
      "Colors": "Red, Blue, Green, Orange (one of each)"},
     [("Will they hold hot soup?", "Yes — silicone is heat-rated to 450°F, well above any hot food temperature."),
      ("Can they be folded for storage?", "Yes — the silicone collapses to about 0.5 in thick for compact pack storage.")],
     "1-year warranty against silicone or rim defects. Heat damage above rated temperature not covered. Non-transferable."),

    (65, "JavaBrew Camp Coffee Press", 35, "TrailChef", "Camp Coffee",
     ["Insulated French press for camp coffee",
      "16-ounce stainless steel construction",
      "Double-walled vacuum insulation keeps coffee hot for 6 hours",
      "Stainless steel mesh filter",
      "Rugged plunger withstands camp conditions",
      "Doubles as a thermos for transport"],
     {"Capacity": "16 oz (475 ml)",
      "Material": "18/8 stainless steel, double-wall vacuum",
      "Filter": "Fine stainless steel mesh",
      "Heat Retention": "6 hours hot, 12 hours cold",
      "Dishwasher Safe": "No (hand wash only)",
      "Weight": "550 g",
      "Color": "Brushed Steel"},
     [("Will this work as a regular thermos?", "Yes — without coffee grounds, it functions as a 16 oz insulated bottle. Coffee residue may affect flavor over time."),
      ("How fine should I grind my coffee?", "Use a coarse grind for French press to prevent fine grounds passing through the mesh filter.")],
     "Lifetime warranty against vacuum insulation failure. Filter mesh and seals warranted for 2 years. Non-transferable."),

    (66, "SaltShaker Seasoning Set", 15, "TrailChef", "Camp Spices",
     ["Five-piece spice and seasoning kit for camping",
      "Salt, pepper, garlic powder, onion powder, mixed herbs",
      "Compact screw-top containers with pour spouts",
      "Total weight under 4 ounces",
      "Refillable for repeat trips",
      "Carrying pouch included"],
     {"Quantity": "5 spices",
      "Spices Included": "Sea salt, black pepper, garlic powder, onion powder, mixed Italian herbs",
      "Container": "Translucent BPA-free plastic with screw-top pour spouts",
      "Capacity per Container": "10 g",
      "Total Weight": "120 g (filled)",
      "Carrying Case": "Drawstring nylon pouch",
      "Refillable": "Yes",
      "Color": "Translucent containers with red caps"},
     [("Can I refill with my own spices?", "Yes — the screw-top containers come apart fully for refilling with bulk spices from home."),
      ("Are the containers waterproof?", "The pour spouts close securely. Submerge-resistant but not fully waterproof; store inside a dry bag for water crossings.")],
     "30-day satisfaction guarantee. Containers warranted against cracking for 1 year. Non-transferable."),

    # ---------- LIGHTING (67-71) ----------
    (67, "NightHawk Headlamp", 50, "BrightTrail", "Headlamp",
     ["350-lumen LED headlamp with rechargeable battery",
      "Five modes: high, medium, low, strobe, red night vision",
      "USB-C rechargeable internal battery",
      "Tilt-down housing aims light where needed",
      "Water-resistant rating IPX4",
      "Up to 70 hours runtime on low"],
     {"Maximum Output": "350 lumens",
      "Beam Distance": "85 m",
      "Battery": "Rechargeable lithium-ion (USB-C)",
      "Runtime (high)": "3 hours",
      "Runtime (low)": "70 hours",
      "Modes": "High, medium, low, strobe, red",
      "Water Resistance": "IPX4",
      "Weight": "85 g",
      "Includes": "USB-C charging cable",
      "Color": "Black/Volcanic Red"},
     [("Can I use replaceable AAA batteries instead?", "No — this model uses a sealed rechargeable battery. The BatteryPro Headlamp is sold separately for AAA compatibility."),
      ("Is the red light bright enough for reading at night?", "Yes — the red mode preserves night vision while providing enough light for trail maps and reading.")],
     "1-year limited warranty against electronic and battery defects. Battery replacement after 500 charge cycles is normal wear. Non-transferable."),

    (68, "CampGlow LED Lantern", 40, "BrightTrail", "Lantern",
     ["1000-lumen rechargeable LED lantern",
      "Three brightness levels and an SOS mode",
      "USB-C charging plus built-in solar panel for off-grid use",
      "10,000 mAh battery doubles as a power bank",
      "Collapsible design for easy storage",
      "IPX5 water-resistant"],
     {"Maximum Output": "1000 lumens",
      "Brightness Modes": "High, medium, low, SOS",
      "Battery": "10,000 mAh lithium-ion",
      "Runtime (high)": "8 hours",
      "Runtime (low)": "30 hours",
      "Charging": "USB-C and integrated solar (slow trickle)",
      "Power Bank": "5V/2A USB-A output",
      "Water Resistance": "IPX5",
      "Weight": "550 g",
      "Color": "Forest Green"},
     [("How long does solar charging take?", "Solar provides supplemental charge only — full sun for 8 hours adds approximately 30% to the battery. USB-C is the primary charging method."),
      ("Can I leave it on all night?", "Yes — at low brightness it runs for 30 hours; perfect for overnight tent illumination.")],
     "2-year limited warranty against electronic defects. Battery is warranted to 80% of original capacity for 1 year. Non-transferable."),

    (69, "StealthBeam Tactical Flashlight", 65, "BrightTrail", "Flashlight",
     ["1500-lumen tactical flashlight",
      "Aircraft-grade aluminum body",
      "Five modes including strobe for emergency use",
      "Adjustable focus from spot to flood",
      "Replaceable 18650 lithium-ion battery",
      "IPX7 water-resistant rating"],
     {"Maximum Output": "1500 lumens",
      "Beam Distance": "300 m",
      "Battery": "1x 18650 lithium-ion (included)",
      "Runtime (high)": "2.5 hours",
      "Runtime (low)": "45 hours",
      "Modes": "Turbo, high, medium, low, strobe",
      "Water Resistance": "IPX7 (1m for 30 min)",
      "Body": "Aircraft-grade aluminum, knurled grip",
      "Weight": "200 g (with battery)",
      "Includes": "Battery, USB-C charger, holster, lanyard",
      "Color": "Anodized Black"},
     [("Is this rechargeable?", "Yes — the included 18650 battery charges via the included USB-C cable directly through a port on the flashlight."),
      ("Can I use other batteries?", "Standard 18650 batteries (3.7V, button-top) work. Do not use protected cells longer than 70mm.")],
     "5-year warranty against body defects and electronic failure. Battery and bulb warranted for 1 year. Non-transferable."),

    (70, "SolarLink Solar Lantern", 55, "BrightTrail", "Solar Light",
     ["Self-contained solar-powered lantern",
      "200-lumen LED output",
      "8-hour solar charge for 12 hours of light",
      "Inflatable collapsible design — packs flat",
      "Hanging loop on top",
      "Doubles as small phone charger"],
     {"Output": "200 lumens",
      "Battery": "1500 mAh lithium-ion",
      "Solar Panel": "Integrated 1.2W panel",
      "Solar Charge Time (full sun)": "8 hours",
      "USB Charge Time": "3 hours",
      "Runtime (high)": "12 hours",
      "Runtime (low)": "30 hours",
      "Phone Charging": "Yes (5V/0.5A — slow charge)",
      "Collapsed Thickness": "1 in",
      "Inflated Height": "5 in",
      "Weight": "150 g",
      "Color": "Translucent White"},
     [("How long does the battery last over years?", "Lithium-ion battery typically lasts 3-5 years before noticeable capacity loss; replace as needed."),
      ("Will it charge in cloudy weather?", "Yes, but at reduced rate — expect 30-50% of full-sun charge speed under heavy cloud cover.")],
     "2-year warranty against panel and electronic defects. Battery warranted for 1 year at 80% of original capacity. Non-transferable."),

    (71, "FireFly String Lights", 25, "BrightTrail", "Decorative Light",
     ["20-foot LED string lights for camp ambiance",
      "30 warm-white LEDs",
      "USB-powered from any 5V power bank or vehicle outlet",
      "Three modes: steady, slow blink, fast blink",
      "Weather-resistant rating IPX4",
      "Lightweight and packable"],
     {"Length": "20 ft",
      "Number of LEDs": "30",
      "Color": "Warm white (2700K)",
      "Power": "USB 5V/0.5A",
      "Modes": "Steady, slow blink, fast blink",
      "Water Resistance": "IPX4",
      "Weight": "85 g",
      "Color": "Translucent housing on copper wire"},
     [("Does it come with a battery pack?", "No — power source is required separately. Use any USB power bank or 12V vehicle USB adapter."),
      ("Are the LEDs replaceable?", "No — the LEDs are integrated into the wire. If a single LED fails, the string continues to function with the remainder.")],
     "1-year limited warranty against LED and electronic defects. Damage from improper power source not covered. Non-transferable."),

    # ---------- TOOLS (72-79) ----------
    (72, "MultiTool Pro 18-in-1", 75, "ToolMaster", "Multi-Tool",
     ["18 functions in a compact stainless steel tool",
      "Pliers, knife, saw, file, screwdrivers, scissors, can opener",
      "All tools lock open for safety",
      "One-handed access to most tools",
      "Includes nylon belt sheath",
      "Made of high-carbon stainless steel"],
     {"Total Functions": "18",
      "Material": "420HC high-carbon stainless steel",
      "Pliers": "Spring-loaded with wire cutter",
      "Blade": "2.5 in straight-edge blade",
      "Saw": "Wood saw and metal file",
      "Screwdrivers": "Phillips, slotted, eyeglass",
      "Other Tools": "Scissors, can opener, bottle opener, ruler, awl, tweezers",
      "Locking": "All tools lock open",
      "Weight": "250 g",
      "Includes": "Nylon belt sheath",
      "Color": "Stainless steel with black liners"},
     [("Is this TSA-approved for carry-on?", "No — multi-tools with blades are prohibited in carry-on luggage. Pack in checked bags only."),
      ("Can I sharpen the blade?", "Yes — 420HC steel sharpens easily with any standard sharpening stone or sharpener.")],
     "Lifetime warranty against tool breakage and material defects. Blade dulling and normal wear not covered. Non-transferable."),

    (73, "NavMaster GPS Device", 300, "ToolMaster", "GPS Navigation",
     ["Handheld GPS with topographic maps preloaded",
      "Sunlight-readable color display",
      "Up to 25 hours of battery life on AA",
      "Waypoint, route, and track logging",
      "Wireless connectivity for smartphone updates",
      "IPX7 water-resistant"],
     {"Display": "2.6 in color, sunlight-readable",
      "GPS Receivers": "GPS, GLONASS, Galileo",
      "Battery": "2x AA (rechargeable or alkaline)",
      "Battery Life": "25 hours (alkaline)",
      "Memory": "16 GB internal, microSD slot",
      "Preloaded Maps": "Topo US 1:24,000",
      "Connectivity": "Bluetooth, USB, ANT+",
      "Water Resistance": "IPX7",
      "Weight": "230 g (with batteries)",
      "Color": "Black with orange accent"},
     [("Does this require a subscription?", "No — basic navigation is included with no subscription. Premium map packs are sold separately."),
      ("Will it work without cell service?", "Yes — GPS works via satellite. No cell service required. Smartphone connectivity is optional for syncing.")],
     "2-year limited warranty against electronic defects. Display and battery contacts are warranted for 1 year. Non-transferable."),

    (74, "BaseLine Compass", 30, "ToolMaster", "Compass",
     ["Standard baseplate compass for orienteering",
      "Liquid-filled capsule for stable readings",
      "Adjustable declination correction",
      "Glow-in-the-dark markings for low-light use",
      "Magnifying lens for map reading",
      "Lanyard included"],
     {"Type": "Baseplate compass with rotating bezel",
      "Capsule": "Liquid-filled (mineral oil)",
      "Declination Adjustment": "Yes (manual screwdriver)",
      "Bezel Resolution": "2-degree increments",
      "Glow Markings": "Phosphorescent",
      "Magnifying Lens": "2.5x integrated",
      "Lanyard": "Included",
      "Dimensions": "4 in x 2.5 in",
      "Weight": "30 g",
      "Color": "Transparent baseplate, red bezel"},
     [("How do I adjust declination?", "Use a small screwdriver to set the declination value for your area (varies by location). Reset annually as magnetic north shifts."),
      ("Will it work near electronics?", "Keep compass away from electronics, large metal objects, and magnets which interfere with the magnetic needle.")],
     "Lifetime warranty against capsule leakage and bezel defects. Magnetic declination drift is not a defect. Non-transferable."),

    (75, "RazorEdge Folding Knife", 60, "ToolMaster", "Folding Knife",
     ["3.5-inch drop-point blade",
      "S30V stainless steel holds an edge",
      "G10 textured handle for grip",
      "Liner-lock with thumb stud opening",
      "Pocket clip for tip-up carry",
      "Belt sheath included"],
     {"Blade Length": "3.5 in",
      "Blade Material": "S30V stainless steel",
      "Hardness": "58-60 HRC",
      "Blade Edge": "Plain edge (drop-point profile)",
      "Handle Material": "G10 textured",
      "Lock Type": "Liner lock",
      "Opening": "Thumb stud (one-handed)",
      "Pocket Clip": "Reversible, tip-up carry",
      "Overall Length": "8 in (open), 4.5 in (closed)",
      "Weight": "120 g",
      "Includes": "Nylon belt sheath",
      "Color": "Black handle, satin blade"},
     [("How sharp is S30V vs other steels?", "S30V offers an excellent balance of edge retention, corrosion resistance, and ease of sharpening. Premium tier — better than 8Cr13MoV, similar to VG-10."),
      ("Is this legal for daily carry?", "Local laws vary. 3.5 in is legal in most US jurisdictions but check your state and local laws.")],
     "Lifetime warranty against blade and lock defects. Edge dulling and rust from improper care are not covered. Non-transferable."),

    (76, "SparkStarter Magnesium Fire Starter", 20, "ToolMaster", "Fire Starter",
     ["Magnesium and ferrocerium fire starter",
      "Works in any weather including rain and snow",
      "Lasts approximately 3,000 strikes",
      "Lanyard for attachment to gear",
      "Compact size for any pack",
      "Survival whistle integrated into handle"],
     {"Material": "Magnesium block with ferrocerium rod",
      "Striker": "Stainless steel scraper (attached)",
      "Approximate Strikes": "3,000",
      "Spark Temperature": "Up to 5,500°F",
      "Length": "4 in",
      "Includes": "Lanyard, integrated survival whistle",
      "Weight": "55 g",
      "Color": "Black"},
     [("How do I use it?", "Scrape magnesium shavings into your tinder, then strike the ferrocerium rod with the back of a knife or the included striker to spark."),
      ("Does it work in rain?", "Yes — both magnesium and ferrocerium spark in any weather. Keep your tinder dry separately.")],
     "Lifetime warranty against rod breakage and striker defects. Consumable use is expected. Non-transferable."),

    (77, "RescueWhistle Emergency Whistle", 10, "ToolMaster", "Emergency Whistle",
     ["120dB pealess emergency whistle",
      "No moving parts — works when wet, cold, or frozen",
      "Plastic body with breakaway lanyard",
      "Audible up to 1 mile in calm conditions",
      "Lifetime guarantee",
      "Bright orange for visibility"],
     {"Sound Output": "120 dB",
      "Type": "Pealess (no internal pea or ball)",
      "Material": "ABS plastic",
      "Lanyard": "Breakaway nylon cord",
      "Effective Range": "Up to 1 mile (calm conditions)",
      "Operates When Wet": "Yes",
      "Operates Frozen": "Yes",
      "Weight": "8 g",
      "Color": "Safety Orange"},
     [("Why pealess?", "Traditional whistles use a small ball that can stick when wet, frozen, or fouled. Pealess design has no internal moving parts to fail."),
      ("Can I attach it to a vest?", "Yes — the lanyard hole accepts standard PFD whistle clips or paracord.")],
     "Lifetime warranty against breakage. Replacement provided free of charge with proof of purchase. Non-transferable."),

    (78, "TrailRepair Sewing Kit", 25, "ToolMaster", "Repair Kit",
     ["Compact field repair kit for outdoor gear",
      "Heavy-duty needles for thick fabric",
      "Bonded nylon thread (high tensile)",
      "Thimble, scissors, safety pins, and patches included",
      "Compact zipper case",
      "Suitable for tents, packs, and outerwear"],
     {"Contents": "12 needles (assorted), 5 spools nylon thread, 4 patches (nylon and fleece), thimble, mini scissors, 6 safety pins",
      "Needle Sizes": "Sharp, ballpoint, leather, blunt-tip",
      "Thread": "Bonded nylon, high-tensile (50 m total)",
      "Patches": "2 self-adhesive nylon, 2 sew-on fleece",
      "Case Material": "Water-resistant zipper pouch",
      "Case Dimensions": "5 in x 3 in x 1 in",
      "Weight": "85 g",
      "Color": "Forest Green"},
     [("Will the patches stick on a wet tent?", "Self-adhesive patches require a dry, clean surface. For wet repairs, use the sew-on fleece patches with bonded nylon thread."),
      ("How long does the thread last?", "50 m total provides enough thread for many small repairs. Refills sold separately.")],
     "1-year warranty against case and tool defects. Consumables (thread, patches, needles) not covered. Non-transferable."),

    (79, "EmergencyKit First Aid Pack", 45, "ToolMaster", "First Aid",
     ["120-piece first aid kit for outdoor use",
      "Waterproof zipper case",
      "Includes bandages, gauze, antiseptic, medications, tools",
      "Quick-reference treatment guide",
      "Suitable for groups up to 4 people for 3 days",
      "Refillable kit components"],
     {"Total Pieces": "120+",
      "Case Material": "Water-resistant nylon with TPU window",
      "Bandages": "Variety pack (40+ pieces)",
      "Gauze and Wraps": "Sterile gauze pads, elastic wrap, triangular bandage",
      "Medications": "Pain reliever, antihistamine, anti-diarrheal, antiseptic wipes",
      "Tools": "Tweezers, scissors, safety pins, CPR mask",
      "Reference": "Quick-treatment guide card",
      "Group Size": "Up to 4 people",
      "Trip Duration": "Up to 3 days",
      "Weight": "550 g",
      "Color": "Safety Red"},
     [("Are medications included?", "Yes — pain reliever (ibuprofen), antihistamine (diphenhydramine), and anti-diarrheal (loperamide). Verify expiration dates annually."),
      ("Is this WFR-approved?", "This is a basic kit suitable for non-technical outdoor use. Wilderness First Responders typically supplement with additional gear.")],
     "1-year limited warranty against case and component defects. Medication expiration is the user's responsibility. Non-transferable."),

    # ---------- SLEEPING ACCESSORIES (80-85) ----------
    (80, "CloudRest Sleeping Pad", 130, "DreamGear", "Sleeping Pad",
     ["Inflatable insulated sleeping pad",
      "R-value of 4.5 for cold-weather use",
      "Twin-chamber baffle design for even support",
      "Self-inflating valve",
      "Stuff sack and patch kit included",
      "Available in regular and large sizes"],
     {"Insulation": "Synthetic fill with reflective layer",
      "R-Value": "4.5",
      "Material": "40D ripstop nylon",
      "Inflation": "Manual valve or built-in pump (sold separately)",
      "Length (regular)": "72 in",
      "Width": "20 in",
      "Thickness": "3 in inflated",
      "Weight": "650 g",
      "Stuff Sack Size": "10 in x 4 in",
      "Comfort Range": "Down to 15°F",
      "Color": "Volcanic Orange"},
     [("Will this work for winter camping?", "R-value of 4.5 is suitable for three-season and shoulder-season cold weather. For deep winter (-20°F and below), pair with a closed-cell foam pad."),
      ("How long does it take to inflate?", "Manual valve takes 8-10 breaths to fully inflate. Built-in pump models inflate in 60 seconds.")],
     "2-year limited warranty against seam failure and valve defects. Punctures and abrasion damage not covered. Non-transferable."),

    (81, "SkyHammock Camping Hammock", 90, "DreamGear", "Hammock",
     ["Single-person camping hammock",
      "Ripstop parachute nylon for strength",
      "Includes tree-friendly straps",
      "Capacity 400 lbs",
      "Carabiners and stuff sack included",
      "Available in single and double sizes"],
     {"Capacity": "400 lbs (single)",
      "Material": "70D ripstop parachute nylon",
      "Length": "10 ft",
      "Width": "5 ft",
      "Tree Straps": "10 ft each (2 included)",
      "Carabiners": "Wire-gate aluminum (2 included)",
      "Stuff Sack": "Integrated",
      "Weight": "650 g",
      "Color Options": "Forest Green, Sky Blue, Volcanic Red"},
     [("Will the straps damage trees?", "The included tree-friendly straps are 1.5 in wide and meet Leave No Trace standards for tree protection."),
      ("Do I need an underquilt?", "For temperatures above 60°F, a hammock alone is comfortable. Below that, an underquilt provides bottom-side insulation that a sleeping bag alone cannot.")],
     "Lifetime warranty against material and stitching defects. Strap webbing warranted for 5 years. Non-transferable."),

    (82, "DreamPouch Camping Pillow", 35, "DreamGear", "Camping Pillow",
     ["Inflatable camping pillow",
      "Soft brushed-polyester top surface",
      "Ergonomic shape supports neck",
      "Compresses to size of a soda can",
      "Adjustable firmness via valve",
      "Stuff sack included"],
     {"Type": "Inflatable with brushed polyester cover",
      "Inflated Dimensions": "16 in x 11 in x 4 in",
      "Compressed Size": "5 in x 2 in (soda can)",
      "Material": "TPU bladder with polyester cover",
      "Inflation": "Manual valve (4-5 breaths)",
      "Weight": "85 g",
      "Color Options": "Charcoal, Sky Blue, Volcanic Red"},
     [("Will it stay inflated all night?", "Yes — quality TPU bladder typically holds air for 8+ hours with no noticeable deflation."),
      ("Can I wash the cover?", "The cover is non-removable. Spot-clean with damp cloth and mild soap; do not submerge.")],
     "1-year warranty against valve and seam defects. Non-transferable."),

    (83, "StormShield Bivy Sack", 180, "DreamGear", "Bivy Sack",
     ["Single-person waterproof bivy bag",
      "Sleeping bag-compatible — extends temperature rating",
      "Hooped face opening for ventilation",
      "Waterproof breathable fabric",
      "Compresses to size of a water bottle",
      "Emergency shelter or sleeping bag protector"],
     {"Capacity": "1 person",
      "Material": "3-layer waterproof breathable nylon",
      "Waterproof Rating": "20,000 mm",
      "Breathability": "10,000 g/m²/24h",
      "Hooped Opening": "Yes (single pole, included)",
      "Floor Material": "Reinforced 70D nylon",
      "Sleeping Bag Compatibility": "Up to 5 in lofted bag",
      "Weight": "750 g",
      "Compressed Size": "10 in x 5 in",
      "Best Use": "Lightweight backpacking, emergency shelter",
      "Color": "Forest Green"},
     [("Is this a tent replacement?", "A bivy is a single-person minimal shelter — less protection from weather than a tent but lighter and faster to set up. Best for solo trips with reliable weather forecasts."),
      ("Will I overheat in summer?", "The hooped face opening provides ventilation. For warm weather, leave the face zipper partially open and pair with a lightweight sleeping bag.")],
     "Lifetime warranty against waterproof membrane failure and seam taping. Pole and zipper warranted for 5 years. Non-transferable."),

    (84, "ThermoMat Insulated Air Mat", 150, "DreamGear", "Sleeping Pad",
     ["Premium air mat with synthetic insulation",
      "R-value of 5.5 for four-season use",
      "Quiet brushed surface — no crinkle sound",
      "Anti-slip bottom prevents sliding on tent floor",
      "Built-in pump bag for inflation",
      "Compact stuff sack"],
     {"Insulation": "Synthetic with thermal reflective layer",
      "R-Value": "5.5",
      "Material": "30D ripstop with TPU coating",
      "Length (regular)": "72 in",
      "Width": "20 in",
      "Thickness": "3.5 in inflated",
      "Inflation": "Pump bag included (60 seconds to inflate)",
      "Weight": "780 g",
      "Comfort Range": "Down to 0°F",
      "Compressed Size": "11 in x 5 in",
      "Color": "Volcanic Red"},
     [("How quiet is it really?", "The brushed-fabric finish eliminates the crinkly sound common to many air mats. Movement is nearly silent."),
      ("Will the pump bag puncture?", "The pump bag is a separate piece from the mat. Inflate by trapping air in the bag, then squeezing into the valve.")],
     "Lifetime warranty against seam failure and material delamination. Punctures from external objects not covered. Non-transferable."),

    (85, "CozyDream Sleeping Bag Liner", 40, "DreamGear", "Sleeping Bag Accessory",
     ["Silk-blend sleeping bag liner",
      "Adds approximately 8°F of warmth",
      "Standalone use as a summer sheet",
      "Keeps sleeping bag clean — extends life",
      "Compresses to fist-size stuff sack",
      "Available in mummy and rectangular shapes"],
     {"Material": "60% mulberry silk, 40% polyester",
      "Shape": "Mummy (fits most sleeping bags)",
      "Length": "84 in",
      "Width": "32 in (top)",
      "Warmth Boost": "Approximately 8°F",
      "Weight": "180 g",
      "Compressed Size": "5 in x 3 in",
      "Color Options": "Charcoal, Burgundy, Sky Blue"},
     [("Will this fit my rectangular bag?", "This is the mummy shape; a rectangular liner is sold as a separate model. Mummy fits most three-season sleeping bags but not wide rectangular bags."),
      ("How do I wash it?", "Machine wash cold on delicate cycle, hang to dry. Do not bleach or tumble dry — silk content is sensitive.")],
     "1-year limited warranty against seam failure. Silk pilling from normal wear is not covered. Non-transferable."),

    # ---------- HYDRATION (86-90) ----------
    (86, "HydroFlask Insulated Water Bottle", 40, "DrinkGear", "Water Bottle",
     ["Double-walled vacuum-insulated stainless steel",
      "Keeps cold for 24 hours, hot for 12",
      "32-ounce capacity with leak-proof lid",
      "Powder-coated exterior resists scratches",
      "Wide mouth fits ice cubes",
      "BPA-free and dishwasher-safe (lid only)"],
     {"Capacity": "32 oz (946 ml)",
      "Material": "18/8 stainless steel, double-wall vacuum",
      "Lid Type": "Wide-mouth flex cap with carry handle",
      "Cold Retention": "24 hours",
      "Hot Retention": "12 hours",
      "Mouth Diameter": "2.25 in (fits ice cubes)",
      "Weight": "440 g (empty)",
      "Color Options": "Glacier Blue, Volcanic Red, Forest Green, Sand"},
     [("Is the entire bottle dishwasher-safe?", "Lid is dishwasher-safe; bottle body is hand-wash only to preserve the powder coating."),
      ("Will the powder coat chip?", "The coating is durable but can chip from drops onto hard surfaces. Cosmetic only — does not affect insulation.")],
     "Lifetime warranty against vacuum insulation failure. Powder coat is warranted for 1 year against peeling. Non-transferable."),

    (87, "AquaTrek Hydration Pack", 80, "DrinkGear", "Hydration Pack",
     ["3-liter bladder hydration pack",
      "Insulated drinking tube prevents freezing",
      "Quick-disconnect bite valve",
      "Removable bladder for easy cleaning",
      "Lightweight pack with 8L of cargo storage",
      "Suitable for trail running and day hikes"],
     {"Bladder Capacity": "3 L (100 oz)",
      "Cargo Capacity": "8 L",
      "Bladder Material": "BPA-free TPU",
      "Tube": "Insulated with quick-disconnect",
      "Bite Valve": "Quick-shut bite valve",
      "Pack Material": "210D ripstop nylon",
      "Weight (empty)": "550 g",
      "Best Use": "Trail running, day hiking, cycling",
      "Color": "Volcanic Red"},
     [("How do I prevent the tube from freezing?", "The insulated tube delays freezing. For below-freezing weather, blow water back into the bladder after each sip."),
      ("Can I drink electrolyte mix from the bladder?", "Yes, but rinse and dry thoroughly after each use to prevent residue and bacterial growth.")],
     "2-year warranty against bladder leakage and pack stitching defects. Bite valve and tube are wear items, warranted for 1 year. Non-transferable."),

    (88, "PurifyPro UV Water Purifier", 100, "DrinkGear", "Water Purification",
     ["Battery-powered UV water purification pen",
      "Treats 1 liter of water in 90 seconds",
      "Kills 99.99% of viruses, bacteria, and protozoa",
      "Rechargeable lithium-ion battery",
      "Up to 50 treatments per charge",
      "USB-C charging"],
     {"Treatment Method": "UV-C light",
      "Effectiveness": "99.99% against viruses, bacteria, protozoa",
      "Treatment Time": "90 seconds per liter",
      "Battery": "Rechargeable lithium-ion (USB-C)",
      "Treatments per Charge": "50",
      "UV Lamp Lifespan": "8,000 treatments",
      "Weight": "115 g",
      "Includes": "USB-C cable, neoprene case",
      "Best Use": "International travel, wilderness backpacking, emergency preparedness",
      "Color": "Volcanic Black"},
     [("Will it work on cloudy water?", "UV requires reasonably clear water. Pre-filter cloudy water through cloth or a basic filter before UV treatment."),
      ("Is it effective against viruses unlike most pump filters?", "Yes — UV is one of the few field methods that kills viruses (e.g., norovirus, hepatitis A) along with bacteria and protozoa.")],
     "2-year warranty against electronic and battery defects. UV lamp is warranted for the rated 8,000 treatments. Non-transferable."),

    (89, "CollapsiBottle Folding Water Bottle", 20, "DrinkGear", "Water Bottle",
     ["Collapsible silicone water bottle",
      "Compresses flat when empty for storage",
      "20-ounce capacity expanded",
      "Carabiner clip included",
      "Dishwasher-safe",
      "BPA-free silicone"],
     {"Material": "Food-grade silicone",
      "Capacity": "20 oz (590 ml) expanded",
      "Compressed Thickness": "0.5 in",
      "Mouth": "Wide-mouth screw cap",
      "Carabiner": "Aluminum clip included",
      "Dishwasher Safe": "Yes",
      "Weight": "85 g",
      "Color Options": "Glacier Blue, Volcanic Orange, Forest Green"},
     [("Can it hold hot liquids?", "Silicone is heat-rated, but the bottle may be too soft to handle when filled with very hot water. Best for cold and room-temperature use."),
      ("Does it taste like silicone?", "When new, a slight silicone aftertaste is possible — wash with warm soapy water 2-3 times before first use.")],
     "1-year warranty against silicone tearing and cap defects. Punctures from sharp objects not covered. Non-transferable."),

    (90, "AquaPure Tablets", 15, "DrinkGear", "Water Purification",
     ["50-tablet pack of chlorine dioxide water purification tablets",
      "Each tablet treats 1 liter of water",
      "Kills viruses, bacteria, protozoa, and Cryptosporidium",
      "30-minute contact time for full disinfection",
      "Cleaner taste than iodine tablets",
      "Lightweight emergency backup"],
     {"Active Ingredient": "Chlorine dioxide",
      "Quantity": "50 tablets",
      "Treatment per Tablet": "1 L of water",
      "Total Capacity": "50 L of treated water",
      "Effective Against": "Viruses, bacteria, protozoa, Cryptosporidium, Giardia",
      "Contact Time": "30 minutes (15 minutes for clear water)",
      "Shelf Life": "5 years (sealed)",
      "Weight": "30 g",
      "Color": "White tablets in foil pack"},
     [("How does this compare to iodine?", "Chlorine dioxide tastes better and is effective against Cryptosporidium (which iodine is not). Iodine is contraindicated for pregnant women and people with thyroid issues."),
      ("Can I use these instead of a filter?", "Tablets are excellent backup but slow (30 minutes). For frequent use, a filter or UV purifier is faster.")],
     "30-day satisfaction guarantee. Tablets are warranted to be effective until the printed expiration date. Non-transferable."),

    # ---------- APPAREL (91-100) ----------
    (91, "WarmCore Thermal Top", 70, "PeakWear", "Base Layer",
     ["Synthetic insulating mid-layer top",
      "Fleece-lined for warmth",
      "Quarter-zip front for ventilation",
      "Thumb loops for layering with shells",
      "Available in five colors",
      "Sizes XS through XXL"],
     {"Material": "Polyester fleece (mid-weight)",
      "Weight Class": "Mid-weight",
      "Closure": "Quarter-zip with chin guard",
      "Thumb Loops": "Yes",
      "Pockets": "1 chest zippered",
      "Sizes": "XS, S, M, L, XL, XXL",
      "Care": "Machine wash cold, tumble dry low",
      "Weight (men's M)": "320 g",
      "Color Options": "Charcoal, Forest Green, Burgundy, Slate Blue, Volcanic Red"},
     [("How does this compare to merino?", "Synthetic fleece dries faster, is more durable, and is less expensive than merino. Merino is naturally odor-resistant; fleece is not."),
      ("Can I wear this as an outer layer in summer?", "Mid-weight fleece is too warm for summer use. Choose the lightweight version for warmer conditions.")],
     "1-year warranty against pilling beyond normal wear and seam failure. Non-transferable."),

    (92, "TrailRunner Hiking Shorts", 50, "PeakWear", "Hiking Apparel",
     ["Lightweight quick-dry hiking shorts",
      "Five pockets including zippered security pocket",
      "Stretch waistband with adjustable belt loops",
      "Inner liner for chafe-free comfort",
      "DWR finish sheds light moisture",
      "Available in 7-inch and 9-inch inseams"],
     {"Material": "Stretch nylon-spandex blend",
      "Weight": "180 g",
      "Inseam Options": "7 in, 9 in",
      "Pockets": "5 (2 hand, 1 zippered security, 2 cargo)",
      "Liner": "Built-in mesh brief liner",
      "Waistband": "Elastic with belt loops",
      "DWR Finish": "Yes",
      "Sizes": "28, 30, 32, 34, 36, 38",
      "Color Options": "Sand, Olive, Slate Grey"},
     [("Are these good for water?", "DWR finish sheds splashes and brief immersion but they're not waterproof. Quick-dry fabric handles unexpected rain or river crossings."),
      ("Will the liner irritate my skin?", "The mesh brief liner uses moisture-wicking polyester. Most users find it comfortable; sensitive skin may prefer to wear separate boxer briefs.")],
     "1-year limited warranty against seam failure and zipper defects. Non-transferable."),

    (93, "SunShield Wide Brim Hat", 35, "PeakWear", "Sun Protection",
     ["UPF 50+ sun protection",
      "3.5-inch brim shades face and neck",
      "Removable chin strap",
      "Mesh ventilation panels",
      "Crushable and packable",
      "Adjustable internal headband"],
     {"UPF Rating": "50+",
      "Brim Width": "3.5 in",
      "Material": "Quick-dry nylon with mesh ventilation",
      "Chin Strap": "Removable, adjustable cord lock",
      "Headband": "Adjustable internal moisture-wicking band",
      "Crushable": "Yes",
      "Sizes": "S/M (head 21-22.5 in), L/XL (22.5-24 in)",
      "Weight": "85 g",
      "Color Options": "Sand, Olive, Khaki"},
     [("Will it stay on in wind?", "The chin strap secures the hat in moderate wind. For strong wind, tighten the strap fully or remove the hat to prevent loss."),
      ("How do I clean it?", "Hand wash with mild soap, reshape while damp, and air-dry. Machine washing can deform the brim.")],
     "1-year warranty against seam failure and material defects. UPF rating is warranted for life of the hat with proper care. Non-transferable."),

    (94, "PeakGrip Insulated Gloves", 60, "PeakWear", "Gloves",
     ["Waterproof insulated gloves for cold-weather activity",
      "Touchscreen-compatible fingertips",
      "Reinforced palm and fingers for durability",
      "Adjustable wrist cinch",
      "Removable liner for two-stage warmth",
      "Available in S, M, L, XL"],
     {"Insulation": "100g synthetic fill",
      "Outer Material": "Waterproof nylon with PU palm",
      "Liner": "Removable fleece (250 g/m²)",
      "Touchscreen": "Yes (thumb and index finger)",
      "Closure": "Adjustable wrist cinch with elastic",
      "Sizes": "S, M, L, XL",
      "Weight (pair, men's M)": "220 g",
      "Comfort Range": "Down to 5°F (active use)",
      "Color": "Black with reflective trim"},
     [("Are they fully waterproof?", "Yes — taped seams and a waterproof outer shell keep hands dry. The removable liner is moisture-wicking but not waterproof on its own."),
      ("Can I wear the liners alone?", "Yes — fleece liners function as standalone gloves for moderate cold or as base-layer hand protection.")],
     "1-year warranty against waterproof membrane failure and seam separation. Non-transferable."),

    (95, "AlpineSocks Merino Wool Socks", 40, "PeakWear", "Socks",
     ["Three-pack of merino wool hiking socks",
      "Cushioned heel and toe",
      "Mid-calf height",
      "Naturally odor-resistant",
      "Reinforced wear zones",
      "Available in S, M, L, XL"],
     {"Quantity": "3 pairs",
      "Material": "78% merino wool, 21% nylon, 1% spandex",
      "Height": "Mid-calf (10 in)",
      "Cushion Zones": "Heel and toe",
      "Wool Weight": "Mid-weight",
      "Sizes": "S (women 6-8), M (women 8-10 / men 6-8.5), L (men 8.5-11), XL (men 11.5-13.5)",
      "Care": "Machine wash cold, tumble dry low",
      "Color": "Charcoal, Olive, Burgundy (one of each)"},
     [("Are these too warm for summer hiking?", "Merino is naturally temperature-regulating. Mid-weight is comfortable in moderate-to-cold weather; for hot weather, choose the lightweight version."),
      ("Will they shrink?", "Pre-shrunk wool minimizes shrinking, but high heat in dryer can shrink up to 1 size. Tumble dry low or air-dry for longest life.")],
     "Lifetime warranty against premature wear in heel and toe areas. Normal wear after 2+ years not covered. Non-transferable."),

    (96, "SunRay Polarized Sunglasses", 90, "PeakWear", "Sunglasses",
     ["Polarized lenses reduce glare on water and snow",
      "100% UV protection",
      "Lightweight TR90 nylon frame",
      "Spring-loaded hinges for secure fit",
      "Includes hard case and microfiber cleaning cloth",
      "Available in mirrored and standard tints"],
     {"Polarization": "Yes",
      "UV Protection": "100% UVA/UVB",
      "Lens Material": "Polycarbonate",
      "Frame Material": "TR90 nylon",
      "Frame Size": "Medium-large (fits most adult faces)",
      "Hinges": "Spring-loaded",
      "Tint": "Polarized brown with gold mirror coating",
      "Includes": "Hard case, microfiber cloth, neoprene strap",
      "Color Options (frames)": "Matte Black, Tortoise"},
     [("Are they good for fishing?", "Yes — polarization reduces glare from water surface, allowing better visibility into the water."),
      ("Can lenses be replaced?", "Lenses are integrated into the frame and not user-replaceable. Send to manufacturer for warranty repair if defective.")],
     "1-year limited warranty against frame and hinge defects. Lens scratches and polarization wear not covered. Non-transferable."),

    (97, "QuickDry Performance T-shirt", 35, "PeakWear", "Apparel",
     ["Quick-drying polyester performance t-shirt",
      "UPF 30 sun protection",
      "Anti-odor treatment",
      "Flatlock seams reduce chafing",
      "Available in short-sleeve and long-sleeve",
      "Sizes XS through XXL"],
     {"Material": "100% polyester (recycled content)",
      "UPF Rating": "30",
      "Anti-Odor": "Silver-ion treatment",
      "Stitching": "Flatlock seams",
      "Sleeve Options": "Short, long",
      "Sizes": "XS, S, M, L, XL, XXL",
      "Weight (men's M, short sleeve)": "150 g",
      "Care": "Machine wash cold, do not bleach, line dry",
      "Color Options": "Charcoal, Forest Green, Slate Blue, Volcanic Red, Sand"},
     [("How does it compare to a cotton t-shirt?", "Quick-dry polyester moves moisture away from skin and dries 5-10x faster than cotton. Better for active use; cotton is more comfortable for casual wear."),
      ("Will the anti-odor treatment wash out?", "Silver-ion treatment is bonded to the fibers and remains effective for the life of the garment, even after many washes.")],
     "1-year warranty against seam failure and treatment fading. Anti-odor effectiveness warranted for 1 year. Non-transferable."),

    (98, "RainShield Pack Cover", 30, "PeakWear", "Pack Accessory",
     ["Waterproof pack cover for rain protection",
      "Available in 35L, 55L, and 75L sizes",
      "Bright color enhances visibility",
      "Elastic edge with cinch cord for secure fit",
      "Compact stuff sack for easy storage",
      "Reflective trim for low-light visibility"],
     {"Sizes Available": "35 L, 55 L, 75 L",
      "Material": "Siliconized nylon ripstop",
      "Waterproof Rating": "10,000 mm",
      "Edge": "Elastic with cinch cord and stop",
      "Reflective Trim": "Yes",
      "Stuff Sack": "Integrated",
      "Weight (55L cover)": "120 g",
      "Color": "Volcanic Orange (also available in Forest Green)"},
     [("Will this fit my 65L pack?", "75L size accommodates packs from 60-80L. The cinch cord allows fitting smaller packs in the same size category."),
      ("Is it waterproof in heavy rain?", "Yes — siliconized nylon with taped seams maintains waterproofing in heavy rain. For multi-day downpours, line your pack interior with a trash compactor bag for double protection.")],
     "Lifetime warranty against material defects and seam failure. Punctures and abrasion damage not covered. Non-transferable."),

    (99, "WindBreak Convertible Pants", 85, "PeakWear", "Hiking Pants",
     ["Convertible hiking pants with zip-off legs",
      "Quick-dry stretch nylon",
      "Six pockets including zippered cargo",
      "DWR finish sheds light moisture",
      "Adjustable hem for boot fit",
      "Available in 30 to 38 waist sizes"],
     {"Material": "Stretch nylon-spandex blend",
      "Convertible": "Zip-off legs (becomes 9-inch shorts)",
      "Weight": "350 g (full pants)",
      "Pockets": "6 (2 hand, 1 zippered security, 2 cargo, 1 back zippered)",
      "DWR Finish": "Yes",
      "Hem": "Adjustable cord lock",
      "Sizes": "30, 32, 34, 36, 38 waist; regular and tall lengths",
      "Color Options": "Sand, Olive, Slate Grey"},
     [("Are the zippers comfortable when worn full-length?", "The thigh zippers lay flat and most users don't notice them when wearing the full pants."),
      ("Can I machine wash them?", "Yes — machine wash cold, tumble dry low. Reapply DWR finish (sold separately) every 6-12 months for continued water resistance.")],
     "1-year warranty against seam failure and zipper defects. DWR coating is warranted for 6 months from first use. Non-transferable."),

    (100, "TrailPro Performance Buff", 20, "PeakWear", "Apparel Accessory",
     ["Multi-functional tubular bandana",
      "Wear as neck gaiter, headband, mask, or wristband",
      "Moisture-wicking microfiber polyester",
      "UPF 25 sun protection",
      "Seamless construction",
      "Eight wear styles included in instructions"],
     {"Material": "Microfiber polyester",
      "UPF Rating": "25",
      "Construction": "Seamless tube",
      "Length": "20 in unstretched",
      "Weight": "30 g",
      "Wear Styles": "Neck gaiter, headband, balaclava, mask, wristband, beanie, bandana, scrunchie",
      "Care": "Machine wash cold, hang to dry",
      "Color Options": "12 patterns available (various)"},
     [("Will it shrink in the wash?", "Pre-shrunk fabric resists shrinkage. Cold wash and air-dry to maximize longevity."),
      ("Is it warm enough for cold weather?", "On its own, the buff provides light warmth. For cold weather, layer multiple buffs or use a fleece-lined version (sold separately).")],
     "1-year warranty against seam failure (rare due to seamless construction). Color fading from prolonged sun exposure is normal. Non-transferable."),
]


# =========================================================================
# Markdown rendering
# =========================================================================

def render_product(p):
    pid, name, price, brand, category, features, specs, faq, warranty = p

    md = f"""# Information about product item_number: {pid}
{name}, price ${price},

## Brand
{brand}

## Category
{category}

## Features
"""
    for f in features:
        md += f"- {f}\n"

    md += "\n## Technical Specs\n"
    for k, v in specs.items():
        md += f"**{k}**: {v}  \n"

    md += "\n## Customer FAQ\n\n"
    for q, a in faq:
        md += f"**Q: {q}**\n\n{a}\n\n"

    md += f"## Warranty Information\n\n{warranty}\n"
    return md


def main():
    OUT_DIR.mkdir(exist_ok=True)
    written = 0
    for p in PRODUCTS:
        pid = p[0]
        path = OUT_DIR / f"product_info_{pid}.md"
        path.write_text(render_product(p), encoding="utf-8")
        written += 1
    print(f"Generated {written} product files in {OUT_DIR}")
    print(f"Catalog now contains {20 + written} total products (1-{20+written}).")


if __name__ == "__main__":
    main()
